### ISSUE TITLE
Similar lists

### ISSUE THREAD

**Issue by Vanuan** [manuzhang/awesome-streaming#6]
Should be merged with similar lists:
* https://github.com/pditommaso/awesome-pipeline/
* https://github.com/pawl/awesome-etl

**Comment by manuzhang** [comment]
Any reason ? I don't see a lot of streaming stuff in those two lists.

**Comment by Vanuan** [comment]
I just thought this list is devoted to tools which helps to set up data pipelines rather than specifically streaming libraries.

**Comment by manuzhang** [comment]
Well, this list is dedicated to everything streaming.

**Comment by Vanuan** [comment]
ok

**Comment by manuzhang** [comment]
I get to know two more lists. That's awesome 😄
