### ISSUE TITLE
Arroyo (distributed stream processing engine) - to add?

### ISSUE THREAD

**Issue by nrenzoni** [manuzhang/awesome-streaming#78]
I just came across the Arroyo project, a "distributed stream processing engine written in Rust". 

https://github.com/ArroyoSystems/arroyo.

Should it be added to the awesome-streaming list?

**Comment by manuzhang** [comment]
Definitely. Would you mind opening a PR?

**Comment by nrenzoni** [comment]
Sure, created a PR here: https://github.com/manuzhang/awesome-streaming/pull/80

**Comment by manuzhang** [comment]
Resolved by #80
